endpoints:
  shutdown:
    enabled: true
spring:
  application:
    name: test-user-service
eureka:
  client:
    service-url:
      #defaultZone: http://${eureka.instance.hostname:eureka.einwin.com}:${eureka.server.port:18761}/eureka/
      defaultZone: http://192.168.5.161:10010/eureka/
  instance:
    prefer-ip-address: true #用ip作为地址
    lease-expiration-duration-in-seconds: 20 #心跳终结最大时间 默认90
    lease-renewal-interval-in-seconds: 10 #心跳间隔 默认30
server:
  port: 10003