endpoints:
  shutdown:
    enabled: true


spring:
  application:
    name: test-role-service

#重试


#熔断
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #熔断 timeout




eureka:
  client:
    service-url:
      defaultZone: http://192.168.5.161:10010/eureka/
  instance:
    prefer-ip-address: true #用ip作为host
server:
  port: 10001