endpoints:
  shutdown:
    enabled: true


spring:
  application:
    name: test-role-service
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB #multipart/form-data 单个文件大小
      max-request-size: 12MB #multipart/form-data 整个内容大小


#重试


#熔断
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #熔断 timeout




eureka:
  client:
    service-url:
      defaultZone: http://192.168.5.161:10010/eureka/
  instance:
    prefer-ip-address: true #用ip作为host
server:
  port: 10001
  tomcat:
    max-http-post-size: 8  # application/x-www-form-urlencoded  <=0 不限制
#mybatis
mybatis:
  mapper-locations: classpath*:mapper/*.xml