endpoints:
  shutdown:
    enabled: true


spring:
  application:
    name: test-role-service
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver


#重试


#熔断
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #熔断 timeout




eureka:
  client:
    service-url:
      defaultZone: http://192.168.5.161:10010/eureka/
  instance:
    prefer-ip-address: true #用ip作为host
server:
  port: 10001